-- Пользователи
CREATE TABLE IF NOT EXISTS users (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     email VARCHAR(254) NOT NULL UNIQUE,
    name VARCHAR(250) NOT NULL
    );

-- Категории
CREATE TABLE IF NOT EXISTS categories (
                                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          name VARCHAR(50) NOT NULL UNIQUE
    );

-- События
CREATE TABLE IF NOT EXISTS events (
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      annotation VARCHAR(2000) NOT NULL,
    category_id BIGINT NOT NULL REFERENCES categories(id),
    created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    description VARCHAR(7000),
    event_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    initiator_id BIGINT NOT NULL REFERENCES users(id),
    lat FLOAT,
    lon FLOAT,
    paid BOOLEAN NOT NULL,
    participant_limit INTEGER NOT NULL DEFAULT 0,
    published_on TIMESTAMP WITHOUT TIME ZONE,
    request_moderation BOOLEAN NOT NULL DEFAULT true,
    state VARCHAR(50) NOT NULL,
    title VARCHAR(120) NOT NULL
    );

-- Запросы на участие
CREATE TABLE IF NOT EXISTS participation_requests (
                                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                      created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                                      event_id BIGINT NOT NULL REFERENCES events(id),
    requester_id BIGINT NOT NULL REFERENCES users(id),
    status VARCHAR(50) NOT NULL,
    UNIQUE (event_id, requester_id)
    );

-- Подборки событий
CREATE TABLE IF NOT EXISTS compilations (
                                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            pinned BOOLEAN NOT NULL,
                                            title VARCHAR(50) NOT NULL UNIQUE
    );

-- Связь подборок и событий
CREATE TABLE IF NOT EXISTS compilations_events (
                                                   compilation_id BIGINT NOT NULL REFERENCES compilations(id),
    event_id BIGINT NOT NULL REFERENCES events(id),
    PRIMARY KEY (compilation_id, event_id)
    );

-- Комменты к событиям
CREATE TABLE IF NOT EXISTS comments (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        content VARCHAR(350) NOT NULL,
    author_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_on TIMESTAMP WITHOUT TIME ZONE,
    state VARCHAR(50) NOT NULL
    );