server.port=9090
spring.application.name=stats-server

# ??????????? ? PostgreSQL ? Docker
spring.datasource.url=jdbc:postgresql://stats-db:5432/stats
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate ?????????
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ??? ???????
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.ru.practicum=DEBUG

# Health endpoint ??? ????????
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always